---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-mco-minio-thanos
  namespace: open-cluster-management-observability
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "600s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: thanos-object-storage # name of the k8s Secret to make in this namespace
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque # type of k8s Secret to make
  data:
    - secretKey: "thanos.yaml"
      remoteRef:
        key: kemo-labs/credentials/mco-minio-thanos # name of the secret under the target Vault path
        property: "thanos.yaml" # name of the key in that named Vault secret
