---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-mco-pull-secret
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "600s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: multiclusterhub-operator-pull-secret # name of the k8s Secret to make in this namespace
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson # type of k8s Secret to make
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: kemo-labs/services/harbor # name of the secret under the target Vault path
        property: pull-secret # name of the key in that named Vault secret

