---
kind: L2Advertisement
apiVersion: metallb.io/v1beta1
metadata:
  name: v60-pool-l2-adv
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  ipAddressPools:
    - v60-pool
---
kind: L2Advertisement
apiVersion: metallb.io/v1beta1
metadata:
  name: v60-hcp-pool-l2-adv
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  ipAddressPools:
    - v60-hcp-auto-pool
