---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/kenmoini/ocp4-gitops-config'
    targetRevision: HEAD
    path: clusters/cluster-poc/config/
    #directory:
    #  recurse: true
    kustomize:
      version: v5.1.0
  project: local-cluster
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      # selfHeal: false # overrides changes made on the cluster that drift from git state
