---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - etcd-defrag.yml
  #- helm-vault.yml
  - nmstate-operator.yml
  - nmstate-instance.yml
  - metallb-operator.yml
  - metallb-instance.yml
  - openshift-virt-operator.yml
  - external-secrets-operator.yml
  - external-secrets-instance.yml
