---
apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: nodepool-sno-three-1
  namespace: sno-three
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  arch: amd64 # amd64 | ppc64le | s390x | arm64
  clusterName: sno-three
  replicas: 1
  management:
    autoRepair: false
    upgradeType: InPlace
  platform:
    type: Agent
    agent:
      agentLabelSelector:
        matchLabels:
          agent-install.openshift.io/bmh: raza-sno-three
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.14.11-multi