---
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataSciencePipelinesApplication
metadata:
  finalizers:
    - datasciencepipelinesapplications.opendatahub.io/finalizer
  name: pipelines-definition
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  apiServer:
    deploy: true
    cABundle:
      configMapName: openshift-service-ca.crt
      configMapKey: service-ca.crt
    stripEOF: true
    dbConfigConMaxLifetimeSec: 120
    applyTektonCustomResource: true
    enableSamplePipeline: true
    autoUpdatePipelineDefaultVersion: true
    archiveLogs: false
    terminateStatus: Cancelled
    enableOauth: true
    trackArtifacts: true
    collectMetrics: true
    injectDefaultScript: true
  database:
    disableHealthCheck: false
    mariaDB:
      deploy: true
      pipelineDBName: mlpipeline
      pvcSize: 10Gi
      username: mlpipeline
  mlmd:
    deploy: false
  objectStorage:
    disableHealthCheck: false
    externalStorage:
      bucket: pipeline-server-storage-bucket
      host: s3.openshift-storage.svc.cluster.local
      port: '443'
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: pipeline-server-storage-bucket
      scheme: https
  persistenceAgent:
    deploy: true
    numWorkers: 1
  scheduledWorkflow:
    cronScheduleTimezone: UTC
    deploy: true
  #mlpipelineUI:
  #  deploy: true