apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-ds-things

resources:
  - namespace.yml
  - trusted-ca-configmap.yml
  - objectbucketclaim.yml
  #- datasciencepipelinesapplication.yml
  - datasciencepipelinesapplication-minio.yml
  #- s3-secret-sync-cronjob.yml