---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: pipeline-server-storage-bucket
  labels:
    app: noobaa
    bucket-provisioner: openshift-storage.noobaa.io-obc
    noobaa-domain: openshift-storage.noobaa.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  objectBucketName: obc-my-ds-things-pipeline-server-storage-bucket
  bucketName: pipeline-server-storage-bucket
  storageClassName: openshift-storage.noobaa.io