---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: noobaa-secret-sync
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: noobaa-secret-sync
  annotations:
    argocd.argoproj.io/sync-wave: "2"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - exec
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: noobaa-secret-sync
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: noobaa-secret-sync
subjects:
  - kind: ServiceAccount
    name: noobaa-secret-sync
    namespace: my-ds-things
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: noobaa-secret-sync
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: noobaa-secret-sync
            image: registry.redhat.io/openshift4/ose-cli:latest
            imagePullPolicy: IfNotPresent
            command:
              - /bin/bash
              - -c
              - |
                #!/usr/bin/env bash

                until oc get secret -n my-ds-things pipeline-server-storage-bucket; do
                    echo "Waiting for pipeline-server-storage-bucket secret to be created"
                    sleep 5
                done

                KEY_ID=$(oc get secret -n my-ds-things pipeline-server-storage-bucket --template={{.data.AWS_ACCESS_KEY_ID}} | base64 -d)
                KEY_SECRET=$(oc get secret -n my-ds-things pipeline-server-storage-bucket --template={{.data.AWS_SECRET_ACCESS_KEY}} | base64 -d)

                cat <<EOF | oc apply -f -
                apiVersion: v1
                kind: Secret
                metadata:
                  name: pipeline-server-s3-secret
                  namespace: my-ds-things
                  labels:
                    opendatahub.io/dashboard: 'true'
                type: Opaque
                stringData:
                  AWS_ACCESS_KEY_ID: ${KEY_ID}
                  AWS_SECRET_ACCESS_KEY: ${KEY_SECRET}
                  AWS_S3_BUCKET: pipeline-server-storage-bucket
                  AWS_S3_ENDPOINT: s3.openshift-storage.svc
                EOF
          serviceAccountName: noobaa-secret-sync
          restartPolicy: OnFailure