---
kind: ConfigMap
apiVersion: v1
metadata:
  name: trusted-ca-bundle
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    config.openshift.io/inject-trusted-cabundle: 'true'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-ca-bundle
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    service.beta.openshift.io/inject-cabundle: 'true'