---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: defrag-etcd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  schedule: "36 9 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: defrag-etcd
            image: registry.redhat.io/openshift4/ose-cli:latest
            imagePullPolicy: IfNotPresent
            command:
              - /bin/bash
              - -c
              - |
                #!/usr/bin/env bash

                oc get pods -l app=etcd -n openshift-etcd --no-headers -o custom-columns=":metadata.name" | while read -r pod ; do
                    oc exec -n openshift-etcd $pod --container etcdctl  -- sh -c "unset ETCDCTL_ENDPOINTS && etcdctl --command-timeout=30s --endpoints=https://localhost:2379 defrag"
                done
          serviceAccountName: defrag-etcd
          restartPolicy: OnFailure
