apiVersion: v1
kind: ConfigMap
metadata:
  name: assisted-service-config
  namespace: multicluster-engine
  labels:
    app: assisted-service
data:
  LOG_LEVEL: "debug"
  AUTH_TYPE: "none"
  SKIP_CERT_VERIFICATION: "True"
  # HTTP_PROXY: "http://proxy.example.com:8080"
  # HTTPS_PROXY: "http://proxy.example.com:8080"
  # NO_PROXY: ""