---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - agentserviceconfig.yaml
  - agent-service-configmap.yaml

patches:
  - path: patch-overrides.yaml
    target:
      kind: MultiClusterEngine
