apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: master-set-max-pods
spec:
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/master: "" 
  kubeletConfig:
    podsPerCore: 30
    maxPods: 500