---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ocp-cluster-admins
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: kemo
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: myAdmin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
