---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: basic-cluster-readers
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: luser
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
