---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: v60-hcp-hypershift
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  addresses:
    - 192.168.60.50/32
  autoAssign: true
  serviceAllocation:
    priority: 50
    namespaces: 
      - clusters-hypershift
---
kind: L2Advertisement
apiVersion: metallb.io/v1beta1
metadata:
  name: v60-pool-l2-adv-hypershift
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  ipAddressPools:
    - v60-hcp-hypershift