---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-cluster-apps-cert
  namespace: openshift-ingress
spec:
  refreshInterval: "600s"
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: apps-lb-tls # name of the k8s Secret to make in this namespace
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: kubernetes.io/tls # type of k8s Secret to make
  data:
    - secretKey: tls.crt
      remoteRef:
        key: kemo-labs/certificates/openshift-clusters/suki-sno.d70.kemo.labs # name of the secret under the target Vault path
        property: tls.bundle.crt # # name of the key in that named Vault secret
    - secretKey: tls.key
      remoteRef:
        key: kemo-labs/certificates/openshift-clusters/suki-sno.d70.kemo.labs # name of the secret under the target Vault path
        property: tls.key # # name of the key in that named Vault secret