---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-ldap-bind-pass
spec:
  refreshInterval: "600s"
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: ldap-bind-password # name of the k8s Secret to make in this namespace
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque # type of k8s Secret to make
  data:
    - secretKey: bindPassword
      remoteRef:
        key: kemo-labs/services/ldap # name of the secret under the target Vault path
        property: bind-pass # # name of the key in that named Vault secret
