apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
spec:
  kustomizeBuildOptions: '--enable-alpha-plugins --enable-helm --helm-command "/usr/local/bin/helm --insecure-skip-tls-verify"'
