---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: image-ps-loe-rdu-sno-one
  namespace: sno-one
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  data:
    - secretKey: .dockerconfigjson # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/ocp-pull-secret # name of the secret under the target Vault path
        property: connected # # name of the key in that named Vault secret
  refreshInterval: 100s
  secretStoreRef:
    kind: ClusterSecretStore # SecretStore or ClusterSecretStore
    name: vault # name of the previousl created SecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: pullsecret-loe-rdu-sno-one # name of the k8s Secret to make in this namespace
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson # type of k8s Secret to make