---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ztp-sso-config
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  labels:
    has-git-repo-objects: "true"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/kenmoini/ocp4-gitops-config'
      targetRevision: HEAD
      path: openshift/rhsso/instance/overlays/ztp
      #directory:
      #  recurse: true
      kustomize:
        version: v5.1.0
  project: local-cluster
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      # selfHeal: false # overrides changes made on the cluster that drift from git state
