---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: instance-mce
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  labels:
    has-git-repo-objects: "true"
spec:
  ignoreDifferences:
    - kind: MultiClusterEngine
      name: multiclusterengine
      jsonPointers:
        - /spec/overrides
  destination:
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/kenmoini/ocp4-gitops-config'
      targetRevision: main
      path: openshift/mce/instance/overlays/kitchen-sink/
      #directory:
      #  recurse: true
      kustomize:
        version: v5.1.0
  project: local-cluster
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
    automated:
      # prune: true
      allowEmpty: true
      # selfHeal: false # overrides changes made on the cluster that drift from git state
