---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: instance-acm
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "31"
  labels:
    has-git-repo-objects: "true"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/kenmoini/ocp4-gitops-config'
      targetRevision: main
      path: openshift/advanced-cluster-management/instance/base/
      #directory:
      #  recurse: true
      kustomize: {}
  project: local-cluster
  syncPolicy:
    automated:
      # prune: true
      allowEmpty: true
      # selfHeal: false # overrides changes made on the cluster that drift from git state
