---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: instance-metallb
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "32"
  labels:
    has-git-repo-objects: "true"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/kenmoini/ocp4-gitops-config'
      targetRevision: HEAD
      path: openshift/metallb/instance/overlays/default/
      #directory:
      #  recurse: true
      kustomize:
        version: v5.1.0
    - repoURL: 'https://github.com/kenmoini/ocp4-gitops-config'
      targetRevision: main
      path: clusters/mega-sno.v60.lab.kemo.network/config/metallb/
      #directory:
      #  recurse: true
      kustomize:
        version: v5.1.0
  project: local-cluster
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
    automated:
      # prune: true
      allowEmpty: true
      # selfHeal: false # overrides changes made on the cluster that drift from git state
