---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-git-config-map.yml
  - 00-etcd-defrag.yml
  - 01-config-machineconfigs.yml
  - 05-lvm-operator.yml
  - 10-lvm-instance.yml
  - 10-config-storageclasses.yml
  #- cluster-config.yml
  #- external-secrets-operator.yml
  #- external-secrets-instance.yml
  #- helm-vault.yml
  #- metallb-operator.yml
  #- metallb-instance.yml
  #- mtv-operator.yml
  #- mtv-instance.yml
  #- nmstate-operator.yml
  #- nmstate-instance.yml
  #- openshift-virt-operator.yml
  #- portworx-operator.yml

replacements:
  - source:
      kind: ConfigMap
      name: git-config
      fieldPath: data.repoBase
    targets:
      - select:
          kind: Application
          group: argoproj.io
          labelSelector: has-git-repo-objects=true
        fieldPaths:
        - spec.sources.*.repoURL
