---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-git-config-map.yml
  - 00-additionaltrustbundle.yml
  - 00-etcd-defrag.yml
  - 01-config-machineconfigs.yml
  - 04-operator-external-secrets.yml
  - 05-instance-external-secrets.yml
  - 05-operator-lvm.yml
  - 06-instance-lvm.yml
  - 07-helm-democratic-csi.yml
  - 10-config-storageclasses.yml
  - 11-operator-pipelines.yml
  - 12-operator-metallb.yml
  - 13-operator-nfd.yml
  - 14-operator-sso.yml
  - 15-operator-aap2.yml
  - 16-operator-gitea.yml
  - 17-operator-acm.yml
  - 18-operator-mce.yml
  - 19-operator-quay.yml
  #- 20-operator-external-dns.yml
  - 21-operator-nmstate.yml
  - 22-operator-mtv.yml
  - 23-operator-openshift-virt.yml
  
  #- 50-instance-metallb.yml
  #- 51-instance-nfd.yml
  #- 10-instance-sso.yml
  #- 30-instance-acm.yml
  #- 30-instance-mce.yml
  #- nmstate-instance.yml
  #- ocp-virt-instance.yml
  #- 50-mtv-instance.yml
  #- 75-virt-config.yml
  #- 100-mco.yml
  #- 100-ztp-sso.yml
  
  #- 50-metallb-config.yml # added in the instance-metallb.yml app
  #- mtv-instance.yml
  #- 50-acm-mce-hcp.yml
  #- cluster-config.yml
  #- external-secrets-operator.yml
  #- external-secrets-instance.yml
  #- helm-vault.yml
  #- metallb-operator.yml
  #- metallb-instance.yml
  #- portworx-operator.yml

replacements:
  - source:
      kind: ConfigMap
      name: git-config
      fieldPath: data.repoBase
    targets:
      - select:
          kind: Application
          group: argoproj.io
          labelSelector: has-git-repo-objects=true
        fieldPaths:
        - spec.sources.*.repoURL
