---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: disconn-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.70.10-192.168.70.20
  autoAssign: false
  #protocol: layer2
