---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  creationTimestamp: null
  name: gitea-operator
  namespace: gitea-operator
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  targetNamespaces:
    - gitea-operator