apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: hub
  namespace: sso
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: sso
spec:
  instances: 1
  profile: RHSSO
  externalAccess:
    enabled: true
  #storageClassName: lvms-vg1-immediate
  keycloakDeploymentSpec:
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 500m
        memory: 512Mi