apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    openshift.io/display-name: "NVIDIA GPU Operator"
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: nvidia-gpu-operator
