apiVersion: hostpathprovisioner.kubevirt.io/v1beta1
kind: HostPathProvisioner
metadata:
  name: hostpath-provisioner
spec:
  storagePools:
    - pvcTemplate:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
      name: local
      path: /var/hpvolumes
  workload:
    nodeSelector:
      kubernetes.io/os: linux
  imagePullPolicy: IfNotPresent
