---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-gcp-oauth-client-secret
spec:
  refreshInterval: "600s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: gcp-oauth-client-secret # name of the k8s Secret to make in this namespace
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque # type of k8s Secret to make
  data:
    - secretKey: clientSecret
      remoteRef:
        key: kemo-labs/credentials/google # name of the secret under the target Vault path
        property: oauth_secret # # name of the key in that named Vault secret
