---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: openshift-config

resources:
  - external-secret.yaml

patches:
  - path: patch-oauth-google.yaml
    target:
      kind: OAuth
