apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-cnv

resources:
  - https://raw.githubusercontent.com/openshift-pipelines/tektoncd-catalog/p/tasks/cleanup-vm/4.16.2/cleanup-vm.yaml
  - https://raw.githubusercontent.com/openshift-pipelines/tektoncd-catalog/p/tasks/copy-template/4.16.2/copy-template.yaml
  - https://raw.githubusercontent.com/openshift-pipelines/tektoncd-catalog/p/tasks/create-vm-from-manifest/4.16.2/create-vm-from-manifest.yaml
  - https://raw.githubusercontent.com/openshift-pipelines/tektoncd-catalog/p/tasks/create-vm-from-template/4.16.2/create-vm-from-template.yaml
  - https://raw.githubusercontent.com/openshift-pipelines/tektoncd-catalog/p/tasks/disk-virt-customize/4.16.2/disk-virt-customize.yaml
  - https://raw.githubusercontent.com/openshift-pipelines/tektoncd-catalog/p/tasks/disk-virt-sysprep/4.16.2/disk-virt-sysprep.yaml
  - https://raw.githubusercontent.com/openshift-pipelines/tektoncd-catalog/p/tasks/modify-data-object/4.16.2/modify-data-object.yaml
  - https://raw.githubusercontent.com/openshift-pipelines/tektoncd-catalog/p/tasks/modify-vm-template/4.16.2/modify-vm-template.yaml
  - https://raw.githubusercontent.com/openshift-pipelines/tektoncd-catalog/p/tasks/modify-windows-iso-file/4.16.2/modify-windows-iso-file.yaml
  - https://raw.githubusercontent.com/openshift-pipelines/tektoncd-catalog/p/tasks/wait-for-vmi-status/4.16.2/wait-for-vmi-status.yaml

  - https://raw.githubusercontent.com/openshift-pipelines/tektoncd-catalog/p/tasks/windows-efi-installer/4.16.2/windows-efi-installer.yaml