apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: rh-pipelines-operator-installed
  namespace: rhacm-config
  annotations:
    policy.open-cluster-management.io/standards: NIST 800-53, NIST-CSF
    policy.open-cluster-management.io/categories: CM Configuration Management, PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration, PR.IP-1 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rh-pipelines-subscription
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: openshift-pipelines-operator-rh
                  namespace: openshift-operators
                spec:
                  channel: latest
                  installPlanApproval: Automatic
                  name: openshift-pipelines-operator-rh
                  source: redhat-operators 
                  sourceNamespace: openshift-marketplace