---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: noobaa-secret-sync
  namespace: openshift-image-registry
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: noobaa-secret-sync
  namespace: openshift-image-registry
  annotations:
    argocd.argoproj.io/sync-wave: "2"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - exec
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: noobaa-secret-sync
  namespace: openshift-image-registry
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: noobaa-secret-sync
subjects:
  - kind: ServiceAccount
    name: noobaa-secret-sync
    namespace: openshift-image-registry
---
apiVersion: batch/v1
kind: Job
metadata:
  name: noobaa-secret-sync
  namespace: openshift-image-registry
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  template:
    spec:
      containers:
      - name: noobaa-secret-sync
        image: registry.redhat.io/openshift4/ose-cli:latest
        imagePullPolicy: IfNotPresent
        command:
          - /bin/bash
          - -c
          - |
            #!/usr/bin/env bash

            until oc get secret -n openshift-image-registry internal-registry-bucket; do
                echo "Waiting for internal-registry-bucket secret to be created"
                sleep 5
            done

            KEY_ID=$(oc get secret -n openshift-image-registry internal-registry-bucket --template={{.data.AWS_ACCESS_KEY_ID}} | base64 -d)
            KEY_SECRET=$(oc get secret -n openshift-image-registry internal-registry-bucket --template={{.data.AWS_SECRET_ACCESS_KEY}} | base64 -d)

            cat <<EOF | oc apply -f -
            apiVersion: v1
            kind: Secret
            metadata:
              name: image-registry-private-configuration-user
              namespace: openshift-image-registry
            type: Opaque
            stringData:
              REGISTRY_STORAGE_S3_ACCESSKEY: ${KEY_ID}
              REGISTRY_STORAGE_S3_SECRETKEY: ${KEY_SECRET}
            EOF
      serviceAccountName: noobaa-secret-sync
      restartPolicy: OnFailure