apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - ../../base

components:
  - ../../components/annotation-resource-tracking
  - ../../components/application-controller-cluster-admin
  - ../../components/cluster-ca-certs
  - ../../components/edge-termination
  - ../../components/enable-notifications
  - ../../components/enable-plugins
  - ../../components/gitops-admins
  - ../../components/health-check-acs-central
  - ../../components/health-check-argocd
  - ../../components/health-check-acm-policy
  - ../../components/health-check-egressips
  - ../../components/health-check-externalsecret
  - ../../components/health-check-nmstate
  - ../../components/health-check-odf
  - ../../components/health-check-olm
  - ../../components/health-check-openshift-builds
  - ../../components/sync-wave-wait
