---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bmc-serenity-dell-r730
  namespace: loe-rdu-dell-r730
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  data:
    - secretKey: username # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/serenity # name of the secret under the target Vault path
        property: bmc-username # # name of the key in that named Vault secret
    - secretKey: password # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/serenity # name of the secret under the target Vault path
        property: bmc-password # # name of the key in that named Vault secret
  refreshInterval: 100s
  secretStoreRef:
    kind: ClusterSecretStore # SecretStore or ClusterSecretStore
    name: vault # name of the previousl created SecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: bmc-serenity-dell-r730 # name of the k8s Secret to make in this namespace
    template:
      engineVersion: v2
      type: Opaque # type of k8s Secret to make