---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: patch-ingress-cert.yml
    target:
      kind: IngressController
      name: default
      namespace: openshift-ingress-operator
