---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  finalizers:
    - ingresscontroller.operator.openshift.io/finalizer-ingresscontroller
  name: default
  namespace: openshift-ingress-operator
spec:
  defaultCertificate:
    name: apps-lb-tls
