---
apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  name: cluster
spec:

  image:
    repository: ghcr.io/external-secrets/external-secrets
    pullPolicy: IfNotPresent
    # -- The image tag to use. The default is the chart appVersion.
    # There are different image flavours available, like distroless and ubi.
    # Please see GitHub release notes for image tags for these flavors.
    # By default the distroless image is used.
    tag: "v0.9.12-ubi"

  prometheus:
    enabled: true
    service:
      port: 8080
  resources:
    requests:
      cpu: 10m
      memory: 96Mi
    limits:
      cpu: 100m
      memory: 256Mi
  extraVolumes:
    - configMap:
        items:
          - key: ca-bundle.crt
            path: tls-ca-bundle.pem
        name: trusted-ca
      name: trusted-ca

  extraVolumeMounts:
    - mountPath: /etc/pki/ca-trust/extracted/pem
      name: trusted-ca
      readOnly: true
