---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-git-config-map.yml
  - 00-additionaltrustbundle.yml
  - 00-etcd-defrag.yml
  - 01-config-machineconfigs.yml
  - 05-operator-lvm.yml
  #- 05-operator-pipelines.yml
  - 05-operator-metallb.yml
  - 05-operator-quay.yml
  - 05-operator-external-secrets.yml
  - 05-operator-external-dns.yml
  - 05-operator-acm.yml
  - 05-operator-mce.yml
  - 05-operator-mtv.yml
  - 05-operator-openshift-virt.yml
  - 10-helm-democratic-csi.yml
  - 10-instance-lvmo.yml
  - 10-instance-metallb.yml
  - 20-instance-mtv.yml
  - 20-instance-openshift-virt.yml
  - 30-instance-acm.yml
  - 30-instance-mce.yml
  #- 10-config-storageclasses.yml
  #- 10-helm-democratic-csi.yml
  #- 10-instance-external-secrets.yml
  #- 20-operator-acm.yml
  #- 20-operator-mce.yml
  #- 30-instance-acm.yml
  #- 30-instance-mce.yml
  #- 50-acm-mce-hcp.yml
  #- cluster-config.yml
  #- openshift-virt-operator.yml

replacements:
  - source:
      kind: ConfigMap
      name: git-config
      fieldPath: data.repoBase
    targets:
      - select:
          kind: Application
          group: argoproj.io
          labelSelector: has-git-repo-objects=true
        fieldPaths:
        - spec.sources.*.repoURL
