# Create the token with the following command:
# oc create secret generic vault-token -n openshift-config --from-literal=token=<token>
# or
# apiVersion: v1
# kind: Secret
# metadata:
#   name: vault-token
#   namespace: openshift-config
# type: Opaque
# stringData:
#   token: <token>
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault
  namespace: openshift-config
spec:
  provider:
    vault:
      auth:
        tokenSecretRef:
          key: token
          name: vault-token
      path: kv/
      server: 'https://vault.kemo.labs:8200'
      version: v2