---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  availabilityConfig: Basic
  #disableUpdateClusterImageSets: false
  #disableHubSelfManagement: true
  #imagePullSecret: cluster-pull-secret
  #enableClusterBackup: false # deprecated
  #separateCertificateManagement: false # deprecated
  #customCAConfigmap: cluster-root-ca-bundle # deprecated
  #overrides:
  #  components:
  #    - enabled: true
  #      name: app-lifecycle
  #    - enabled: false
  #      name: search
  #    - enabled: true
  #      name: console
  #    - enabled: false
  #      name: insights
  #    - enabled: true
  #      name: grc
  #    - enabled: true
  #      name: cluster-lifecycle
  #    - enabled: false
  #      name: volsync
  #    - enabled: true
  #      name: multicluster-engine
  #    - enabled: false
  #      name: cluster-proxy-addon
  #    - enabled: false
  #      name: cluster-backup