---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  availabilityConfig: Basic
  #disableUpdateClusterImageSets: false
  #disableHubSelfManagement: true
  #imagePullSecret: cluster-pull-secret
  #enableClusterBackup: false # deprecated
  #separateCertificateManagement: false # deprecated
  #customCAConfigmap: cluster-root-ca-bundle # deprecated
  overrides:
    components:
      - enabled: true
        name: app-lifecycle
      - enabled: true
        name: cluster-lifecycle
      - enabled: true
        name: cluster-permission
      - enabled: true
        name: console
      - enabled: true
        name: grc
      - enabled: false
        name: insights
      - enabled: true
        name: multicluster-engine
      - enabled: false
        name: multicluster-observability
      - enabled: false
        name: search
      - enabled: false
        name: submariner-addon
      - enabled: false
        name: volsync
      - enabled: false
        name: cluster-backup