---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: external-dns-operator

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable-v1'
    target:
      kind: Subscription
      name: external-dns-operator
