---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: additional-trust-bundle
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    has-git-repo-objects: "true"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/kenmoini/ocp4-gitops-config'
      targetRevision: main
      path: clusters/suki-sno.v60.lab.kemo.network/config/proxy-config/overlays/additional-trust-bundle/
      #directory:
      #  recurse: true
      kustomize:
        version: v5.1.0
    - repoURL: 'https://github.com/kenmoini/ocp4-gitops-config'
      targetRevision: main
      path: clusters/suki-sno.v60.lab.kemo.network/config/image-config/overlays/additional-trust-bundle/
      #directory:
      #  recurse: true
      kustomize:
        version: v5.1.0
  project: local-cluster
  syncPolicy:
    automated:
      prune: false
      allowEmpty: true
      # selfHeal: false # overrides changes made on the cluster that drift from git state
