---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-reflector
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: 'reflector'
    server: https://kubernetes.default.svc
  project: local-cluster
  sources:
    - chart: reflector
      helm: {}
      repoURL: 'https://emberstack.github.io/helm-charts'
      targetRevision: 7.1.262
    - repoURL: 'https://github.com/kenmoini/ocp4-gitops-config'
      targetRevision: main
      path: clusters/raza-gpu-sno.kemo.labs/20-config/reflector/
      #directory:
      #  recurse: true
      kustomize: {}
  syncPolicy:
    automated:
      allowEmpty: true
      #prune: false
    syncOptions:
      - CreateNamespace=true