---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-vsphere
  namespace: openshift-mtv
spec:
  refreshInterval: "600s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: rdu-lab-vsphere # name of the k8s Secret to make in this namespace
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque # type of k8s Secret to make
  data:
    - secretKey: cacert
      remoteRef:
        key: kemo-labs/credentials/vsphere # name of the secret under the target Vault path
        property: cacert # name of the key in that named Vault secret
    - secretKey: insecureSkipVerify
      remoteRef:
        key: kemo-labs/credentials/vsphere
        property: insecureSkipVerify
    - secretKey: password
      remoteRef:
        key: kemo-labs/credentials/vsphere
        property: password
    - secretKey: url
      remoteRef:
        key: kemo-labs/credentials/vsphere
        property: sdkurl
    - secretKey: user
      remoteRef:
        key: kemo-labs/credentials/vsphere
        property: user
