---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: openshift-config

# Provided users are:
## myAdmin / s0m3P455
## luser / notAGoodPassword

resources:
  - htpasswd-secret.yaml

patches:
  - path: patch-oauth-htpasswd.yaml
    target:
      kind: OAuth
