kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: image-registry
  namespace: openshift-image-registry
  finalizers:
    - kubernetes.io/pvc-protection
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 75Gi
  volumeMode: Filesystem
  #storageClassName: lvms-vg1