---
kind: Secret
apiVersion: v1
metadata:
  name: vault-token
  namespace: external-secrets
stringData:
  token: hvs.CAESILA8TA_wX_P7dVyp_XPe5ahne4b9huqiEpIO35f-FYrFGh4KHGh2cy45SXZUTUQyTzFmMUQxb3VyWjB1UzdHVnY
type: Opaque