kind: ClusterSecretStore
apiVersion: external-secrets.io/v1beta1
metadata:
  name: vault
spec:
  provider:
    vault:
      auth:
        tokenSecretRef:
          key: token
          name: vault-token
          namespace: external-secrets
      # caBundle: ...
      path: kv
      server: 'http://vault.apps.k8s.kemo.labs'
      version: v2
