---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: openshift-config

# Don't use a secretGenerator since the name is not predictable
#secretGenerator:
#- name: matrix-login-template
#  files:
#  - login.html

resources:
  - matrix-login-template-secret.yaml

patches:
  - path: patch-login-template.yaml
    target:
      kind: OAuth
